function [ output_args ] = setParameters(filename, x)
%SETPARAMETERS Summary of this function goes here
%   Detailed explanation goes here

    mask = [1 1 1 1 ...
...
        1 1 1 1 ...
        1 1 1 1 ...
        1 1 1 1 ...
        1 1 1 1 ...
...   
        1 1 1 1 ...
        1 1 1 0 ... 
        1 1 1 0 ... 
        1 1 1 0 ... 
...
        0 0 0 0 ... 
...     
        0 0 0 0 ... 
...     
        0 0 0 0 ... 
...     
        1 1 1 1 ... 
...     
        0 0 0 0];  
   

    system(['./setParameters ', filename, ' ', num2str(length(x)), ' ', num2str(x), ' ', num2str(mask)]);
       
end

